- name: Install benchmarker
  shell: |
    /usr/local/go/bin/go build -o /tmp/benchmarker cmd/bench/main.go && mv /tmp/benchmarker bin/benchmarker
  args:
    chdir: /home/isucon/isucari
  environment:
    GO111MODULE: "on"
  become: yes
  become_user: isucon
