name: isucari
services:
  payment:
    build:
      context: .
      dockerfile: bench/Dockerfile-payment
    ports:
      - "5556:5556"

  shipment:
    build:
      context: .
      dockerfile: bench/Dockerfile-shipment
    ports:
      - "7002:7002"
