- name: Increase file limits for sysctl
  copy:
    dest: /etc/sysctl.d/50-fs.conf
    content: |
      fs.file-max=655360

- name: Tune up network
  become: yes
  copy:
    dest: /etc/sysctl.d/92-net.conf
    content: |
      net.core.somaxconn=65535

- name: Increase file limits
  become: yes
  copy:
    dest: /etc/security/limits.d/50-nofile.conf
    content: |
      isucon hard nofile 10000
      isucon soft nofile 10000
